version: "3"
services:
  db:
    image: postgres
    container_name: "postgres-container"
    environment:
      - POSTGRES_DB=db_waproject
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - '5432:5432'
    restart: always
    networks:
      - backend
  api:
    image: node:10-slim
    container_name: "node-container"
    ports:
      - '3333:3333'
    working_dir: '/home/node/app'
    volumes:
      - ./:/home/node/app
    command: 'yarn migration'
    networks:
      - backend
      
networks:
  backend:
    driver: 'bridge'

